const List<Map<String, dynamic>> egyptLocations = [
  {
    "ar": "القاهرة",
    "en": "Cairo",
    "cities": [
      {"ar": "مدينة نصر", "en": "Nasr City"},
      {"ar": "حلوان", "en": "Helwan"},
      {"ar": "المعادي", "en": "Maadi"},
      {"ar": "الزمالك", "en": "Zamalek"},
      {"ar": "شبرا", "en": "Shubra"},
      {"ar": "المرج", "en": "El Marg"},
      {"ar": "عين شمس", "en": "Ain Shams"},
      {"ar": "العباسية", "en": "Abbaseya"},
      {"ar": "الشروق", "en": "El Shorouk"},
      {"ar": "15 مايو", "en": "15 May"},
      {"ar": "التجمع الخامس", "en": "5th Settlement"},
      {"ar": "مصر الجديدة", "en": "Heliopolis"},
      {"ar": "القطامية", "en": "Kattameya"},
      {"ar": "التبين", "en": "El Tebbain"},
      {"ar": "روض الفرج", "en": "Rod El Farag"},
      {"ar": "باب الشعرية", "en": "Bab El Shaaria"},
    ],
  },
  {
    "ar": "الجيزة",
    "en": "Giza",
    "cities": [
      {"ar": "6 أكتوبر", "en": "6th of October"},
      {"ar": "الهرم", "en": "Al Haram"},
      {"ar": "المهندسين", "en": "Mohandessin"},
      {"ar": "الشيخ زايد", "en": "Sheikh Zayed"},
      {"ar": "البدرشين", "en": "Badrashin"},
      {"ar": "الحوامدية", "en": "Hawamdiyah"},
      {"ar": "العجوزة", "en": "Agouza"},
      {"ar": "إمبابة", "en": "Imbaba"},
      {"ar": "أطفيح", "en": "Atfih"},
      {"ar": "بولاق الدكرور", "en": "Boulak El Dakrour"},
      {"ar": "منشأة القناطر", "en": "Monshe'at El Kanater"},
      {"ar": "أوسيم", "en": "Ousim"},
      {"ar": "كرداسة", "en": "Kerdasa"},
    ],
  },
  {
    "ar": "الإسكندرية",
    "en": "Alexandria",
    "cities": [
      {"ar": "الإسكندرية", "en": "Alexandria"},
      {"ar": "سيدي بشر", "en": "Sidi Bishr"},
      {"ar": "محرم بك", "en": "Moharam Bek"},
      {"ar": "ميامي", "en": "Miami"},
      {"ar": "المنتزه", "en": "Montazah"},
      {"ar": "العجمي", "en": "Agami"},
      {"ar": "سموحة", "en": "Smouha"},
      {"ar": "برج العرب", "en": "Borg El Arab"},
      {"ar": "كفر الدوار", "en": "Kafr El Dawwar"},
      {"ar": "أبو قير", "en": "Abu Qir"},
      {"ar": "العامرية", "en": "Ameriya"},
    ],
  },
  {
    "ar": "الدقهلية",
    "en": "Dakahlia",
    "cities": [
      {"ar": "المنصورة", "en": "Mansoura"},
      {"ar": "طلخا", "en": "Talkha"},
      {"ar": "ميت غمر", "en": "Meet Ghamr"},
      {"ar": "أجا", "en": "Aga"},
      {"ar": "السنبلاوين", "en": "Sinbillawin"},
      {"ar": "منية النصر", "en": "Menyet El Nasr"},
      {"ar": "بلقاس", "en": "Belqas"},
      {"ar": "دكرنس", "en": "Dekernes"},
      {"ar": "جمصة", "en": "Gamasa"},
    ],
  },
  {
    "ar": "الشرقية",
    "en": "Sharqia",
    "cities": [
      {"ar": "الزقازيق", "en": "Zagazig"},
      {"ar": "العاشر من رمضان", "en": "10th of Ramadan"},
      {"ar": "بلبيس", "en": "Belbeis"},
      {"ar": "أبو حماد", "en": "Abu Hammad"},
      {"ar": "فاقوس", "en": "Fakous"},
      {"ar": "منيا القمح", "en": "Minya El Qamh"},
      {"ar": "منشأة أبو عمر", "en": "Manshiyet Abu Omar"},
      {"ar": "أولاد صقر", "en": "Oulad Saqr"},
      {"ar": "كفر صقر", "en": "Kafr Saqr"},
      {"ar": "الحسينية", "en": "Husseiniya"},
    ],
  },
  {
    "ar": "الغربية",
    "en": "Gharbia",
    "cities": [
      {"ar": "طنطا", "en": "Tanta"},
      {"ar": "المحلة الكبرى", "en": "El Mahalla El Kubra"},
      {"ar": "زفتى", "en": "Zefta"},
      {"ar": "كفر الزيات", "en": "Kafr El Zayat"},
      {"ar": "قطور", "en": "Qutur"},
      {"ar": "بسيون", "en": "Basyoun"},
      {"ar": "السنطة", "en": "El Santa"},
      {"ar": "سمنود", "en": "Samannoud"},
    ],
  },
  {
    "ar": "المنوفية",
    "en": "Monufia",
    "cities": [
      {"ar": "شبين الكوم", "en": "Shibin El Kom"},
      {"ar": "منوف", "en": "Menouf"},
      {"ar": "أشمون", "en": "Ashmon"},
      {"ar": "السادات", "en": "Sadat City"},
      {"ar": "بركة السبع", "en": "Berkat El Sabe"},
      {"ar": "تلا", "en": "Tala"},
      {"ar": "الباجور", "en": "El Bagour"},
      {"ar": "قويسنا", "en": "Quesna"},
    ],
  },
  {
    "ar": "كفر الشيخ",
    "en": "Kafr El Sheikh",
    "cities": [
      {"ar": "كفر الشيخ", "en": "Kafr El Sheikh"},
      {"ar": "دسوق", "en": "Desouk"},
      {"ar": "برج البرلس", "en": "Burg El Burullus"},
      {"ar": "مصيف كفر الشيخ", "en": "Kafr El Sheikh Resort"},
      {"ar": "قلين", "en": "Qallin"},
      {"ar": "فوه", "en": "Fuwah"},
      {"ar": "مطوبس", "en": "Metoubes"},
    ],
  },
  {
    "ar": "القليوبية",
    "en": "Qalyubia",
    "cities": [
      {"ar": "بنها", "en": "Banha"},
      {"ar": "شبرا الخيمة", "en": "Shubra El Kheima"},
      {"ar": "قليوب", "en": "Qalyub"},
      {"ar": "القناطر الخيرية", "en": "El Qanater El Khayreya"},
      {"ar": "الخانكة", "en": "El Khanka"},
      {"ar": "كفر شكر", "en": "Kafr Shukr"},
      {"ar": "طوخ", "en": "Tukh"},
    ],
  },
  {
    "ar": "البحيرة",
    "en": "Beheira",
    "cities": [
      {"ar": "دمنهور", "en": "Damanhur"},
      {"ar": "كفر الدوار", "en": "Kafr El Dawwar"},
      {"ar": "إدكو", "en": "Edfina"},
      {"ar": "الرحمانية", "en": "El Rahmaniya"},
      {"ar": "حوش عيسى", "en": "Housh Eissa"},
      {"ar": "وادي النطرون", "en": "Wadi El Natrun"},
      {"ar": "أبو المطامير", "en": "Abu El Matamir"},
    ],
  },
  {
    "ar": "الفيوم",
    "en": "Faiyum",
    "cities": [
      {"ar": "الفيوم", "en": "Faiyum"},
      {"ar": "إطسا", "en": "Etsa"},
      {"ar": "سنورس", "en": "Sinnuris"},
      {"ar": "طامية", "en": "Tamiya"},
      {"ar": "إبشواي", "en": "Ibsheway"},
      {"ar": "يوسف الصديق", "en": "Youssef El Seddik"},
      {"ar": "الفيوم الجديدة", "en": "New Faiyum"},
    ],
  },
  {
    "ar": "بني سويف",
    "en": "Beni Suef",
    "cities": [
      {"ar": "بني سويف", "en": "Beni Suef"},
      {"ar": "الواسطى", "en": "El Wasta"},
      {"ar": "إهناسيا", "en": "Ehnasia"},
      {"ar": "ببا", "en": "Beba"},
      {"ar": "سمسطا", "en": "Samasta"},
      {"ar": "الفشن", "en": "El Fashn"},
      {"ar": "بني سويف الجديدة", "en": "New Beni Suef"},
    ],
  },
  {
    "ar": "المنيا",
    "en": "Minya",
    "cities": [
      {"ar": "المنيا", "en": "El Minya"},
      {"ar": "ملوي", "en": "Mallawi"},
      {"ar": "سمالوط", "en": "Samalut"},
      {"ar": "أبو قرقاص", "en": "Abu Qirqas"},
      {"ar": "مطاي", "en": "Mattay"},
      {"ar": "مغاغة", "en": "Maghagha"},
      {"ar": "دير مواس", "en": "Deir Mawas"},
    ],
  },
  {
    "ar": "أسيوط",
    "en": "Asyut",
    "cities": [
      {"ar": "أسيوط", "en": "Asyut"},
      {"ar": "ديروط", "en": "Dairut"},
      {"ar": "القوصية", "en": "El Qusiya"},
      {"ar": "منفلوط", "en": "Manfalut"},
      {"ar": "أبو تيج", "en": "Abu Tig"},
      {"ar": "الغنايم", "en": "El Ghanayem"},
      {"ar": "صدفا", "en": "Sidfa"},
    ],
  },
  {
    "ar": "سوهاج",
    "en": "Sohag",
    "cities": [
      {"ar": "سوهاج", "en": "Sohag"},
      {"ar": "جرجا", "en": "Girga"},
      {"ar": "أخميم", "en": "Akhmim"},
      {"ar": "طهطا", "en": "Tahta"},
      {"ar": "البلينا", "en": "El Balyna"},
      {"ar": "دار السلام", "en": "Dar El Salam"},
      {"ar": "ساقلتة", "en": "Saqultah"},
    ],
  },
  {
    "ar": "قنا",
    "en": "Qena",
    "cities": [
      {"ar": "قنا", "en": "Qena"},
      {"ar": "نجع حمادي", "en": "Nag Hammadi"},
      {"ar": "قوص", "en": "Qus"},
      {"ar": "نقادة", "en": "Naqada"},
      {"ar": "قفط", "en": "Qift"},
      {"ar": "أبو تشت", "en": "Abu Tesht"},
      {"ar": "دشنا", "en": "Deshna"},
    ],
  },
  {
    "ar": "الأقصر",
    "en": "Luxor",
    "cities": [
      {"ar": "الأقصر", "en": "Luxor"},
      {"ar": "القرنة", "en": "El Qarna"},
      {"ar": "أرمنت", "en": "Armant"},
      {"ar": "إسنا", "en": "Esna"},
      {"ar": "البياضية", "en": "El Bayadeya"},
      {"ar": "الزينية", "en": "El Ziniyya"},
    ],
  },
  {
    "ar": "أسوان",
    "en": "Aswan",
    "cities": [
      {"ar": "أسوان", "en": "Aswan"},
      {"ar": "كوم أمبو", "en": "Kom Ombo"},
      {"ar": "إدفو", "en": "Edfu"},
      {"ar": "دراو", "en": "Daraw"},
      {"ar": "نصر النوبة", "en": "Nasr El Nuba"},
    ],
  },
  {
    "ar": "البحر الأحمر",
    "en": "Red Sea",
    "cities": [
      {"ar": "الغردقة", "en": "Hurghada"},
      {"ar": "رأس غارب", "en": "Ras Ghareb"},
      {"ar": "سفاجا", "en": "Safaga"},
      {"ar": "القصير", "en": "El Quseir"},
      {"ar": "مرسى علم", "en": "Marsa Alam"},
      {"ar": "الشلاتين", "en": "Shalateen"},
      {"ar": "حلايب", "en": "Halayeb"},
    ],
  },
  {
    "ar": "الوادى الجديد",
    "en": "New Valley",
    "cities": [
      {"ar": "الخارجة", "en": "El Kharga"},
      {"ar": "الداخلة", "en": "El Dakhla"},
      {"ar": "الفرافرة", "en": "Farafra"},
      {"ar": "باريس", "en": "Paris"},
      {"ar": "بلاط", "en": "Balat"},
    ],
  },
  {
    "ar": "مطروح",
    "en": "Matrouh",
    "cities": [
      {"ar": "مرسى مطروح", "en": "Marsa Matrouh"},
      {"ar": "الضبعة", "en": "El Dabaa"},
      {"ar": "العلمين", "en": "El Alamein"},
      {"ar": "سيوة", "en": "Siwa"},
      {"ar": "الحمام", "en": "El Hammam"},
      {"ar": "براني", "en": "Barani"},
    ],
  },
  {
    "ar": "شمال سيناء",
    "en": "North Sinai",
    "cities": [
      {"ar": "العريش", "en": "Arish"},
      {"ar": "بئر العبد", "en": "Bir al-Abed"},
      {"ar": "الشيخ زويد", "en": "Shaykh Zuwayd"},
      {"ar": "رفح", "en": "Rafah"},
      {"ar": "الحسنة", "en": "Al Hasana"},
      {"ar": "نخل", "en": "Nakhl"},
    ],
  },
  {
    "ar": "جنوب سيناء",
    "en": "South Sinai",
    "cities": [
      {"ar": "الطور", "en": "El Tor"},
      {"ar": "شرم الشيخ", "en": "Sharm El Sheikh"},
      {"ar": "دهب", "en": "Dahab"},
      {"ar": "نويبع", "en": "Nuweiba"},
      {"ar": "سانت كاترين", "en": "Saint Catherine"},
      {"ar": "طابا", "en": "Taba"},
      {"ar": "رأس سدر", "en": "Ras Sudr"},
    ],
  },
  {
    "ar": "دمياط",
    "en": "Damietta",
    "cities": [
      {"ar": "دمياط", "en": "Damietta"},
      {"ar": "فارسكور", "en": "Farskour"},
      {"ar": "كفر سعد", "en": "Kafr Saad"},
      {"ar": "الزرقا", "en": "El Zarqa"},
      {"ar": "رأس البر", "en": "Ras El Bar"},
    ],
  },
  {
    "ar": "بورسعيد",
    "en": "Port Said",
    "cities": [
      {"ar": "بورسعيد", "en": "Port Said"},
      {"ar": "بورفؤاد", "en": "Port Fouad"},
    ],
  },
  {
    "ar": "الإسماعيلية",
    "en": "Ismailia",
    "cities": [
      {"ar": "الإسماعيلية", "en": "Ismailia"},
      {"ar": "فايد", "en": "Faid"},
      {"ar": "القنطرة شرق", "en": "El Qantara Sharq"},
      {"ar": "التل الكبير", "en": "El Tal El Kebir"},
      {"ar": "أبو صوير", "en": "Abu Suweir"},
    ],
  },
  {
    "ar": "السويس",
    "en": "Suez",
    "cities": [
      {"ar": "السويس", "en": "Suez"},
      {"ar": "حي عتاقة", "en": "Ataka District"},
      {"ar": "العين السخنة", "en": "Ain Sokhna"},
      {"ar": "حي الجناين", "en": "El Ganayen District"},
    ],
  },
];
