// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVf0an5zJCMrCFa0_ORjTipUJoptqJUc',
    appId: '1:1012204243775:web:f1ea1eaebb97fa489fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    authDomain: 'suits-d4a64.firebaseapp.com',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    measurementId: 'G-1JPBZ1Y1CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80oMMqepsM0THIlTLI872qz-km8PN07I',
    appId: '1:1012204243775:android:7a38fd295e6b26799fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bGX6APRl1RrQ4GdZw9N3ZeCd65bG86o',
    appId: '1:1012204243775:ios:67767b320efb702e9fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    iosClientId: '1012204243775-r718jp7e1gjes90nti57pd4bo5pdqevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.suits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1bGX6APRl1RrQ4GdZw9N3ZeCd65bG86o',
    appId: '1:1012204243775:ios:67767b320efb702e9fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    iosClientId: '1012204243775-r718jp7e1gjes90nti57pd4bo5pdqevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.suits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsVf0an5zJCMrCFa0_ORjTipUJoptqJUc',
    appId: '1:1012204243775:web:308b64d7ec63cca79fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    authDomain: 'suits-d4a64.firebaseapp.com',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    measurementId: 'G-H9XTPNF44N',
  );
}
